title: Huanyu Li's Homepage
page-top-title: Huanyu LI
top-section-bg-text: Electronic Information Engineering
home-subtitle: Huanyu LI&ensp;|&ensp;李桓宇
copyright-text: '&copy; Huanyu Li 2024. All Rights Reserved.'
